### ISSUE TITLE
Can't use `@since` in WIT world

### ISSUE THREAD

**Issue by benbrandt** [bytecodealliance/componentize-py#101]
Hi, we are trying to create a component that uses a WIT world that has `@since` and we can't compile.

```
AssertionError: expected world,interface or use, found @
```

I know that this is a new feature. Is it possible that there is a simple update necessary on a crate or something to support this?

**Comment by dicej** [comment]
Thanks for reporting this @benbrandt.  Yeah, looks like we need to update the `wit-parser` dep at minimum, and that will probably cascade to other updates to keep everything compatible.  It probably won't be simple, since those deps will almost certainly bring API changes, but no point in postponing it.

I'll take a stab at that when I get a chance, probably in the next couple of days.

**Comment by benbrandt** [comment]
@dicej in an effort to provide a solution to the problem I raised, I did my best to get started: https://github.com/bytecodealliance/componentize-py/pull/102

I'm not sure if it is helpful, as I suspect I messed something up since there is one failing test on my machine. If it is a helpful starting point, great. If not, no worries. It was a fun learning experience going through your codebase

**Comment by benbrandt** [comment]
@dicej I can confirm this is now properly working with the 0.14 release. Thanks!
