### ISSUE TITLE
Update to official Cpython wasi builds

### ISSUE THREAD

**Issue by benbrandt** [bytecodealliance/componentize-py#115]
I saw that as of 3.13, wasi is a tier 2 target, and there appear to be builds here: https://github.com/brettcannon/cpython-wasi-build

Would this solve the need for a fork with patches for sockets? Or are you patches still necessary?

Updating to 3.13 would also mean needing to update the wasi-wheels repo (as we've found the version of pydantic there doesn't build on mac on 3.13 at least), but I just wanted to get your feedback on if it is possible to start utilizing the new builds.

Happy to do the experiment, but wanted to check in first. Thanks!

**Comment by dicej** [comment]
My patches are still necessary to support sockets.  Brett considered adding WASI socket support upstream but decided not to since the vast majority of the sockets tests in the CPython test suite require multithreading, and WASI doesn't have that yet.  There's also the challenge of communicating to users that WASI has sockets, but that they're only really useful via `asyncio`.  In short, the requirements for supporting sockets upstream are more stringent than they are for this project, and we probably won't reach that bar until we have multithreading.

We can definitely rebase my (fairly trivial) patches onto 3.13, though.
