### ISSUE TITLE
name of the script

### ISSUE THREAD

**Issue by henderiw** [bytecodealliance/componentize-py#131]
I am a newbie so bear with me, but when I run componentize-py with the name of the script equal to the name of the world/wasm file I get this error

(.venv) (base) python/reconciler > componentize-py --wit-path ../../../wit --world reconciler componentize reconciler -o reconciler.wasm
Traceback (most recent call last):
  File "/Users/henderiw/code/wasm/component-reconciler/guest/python/reconciler/.venv/bin/componentize-py", line 8, in <module>
    sys.exit(script())
             ^^^^^^^^
AssertionError: 

Caused by:
    TypeError: Can't instantiate abstract class Reconciler without an implementation for abstract method 'reconcile'
    
 
When I rename the script name to rec.py it works w/o error and I generate the .wasm file

(.venv) (base) python/reconciler > componentize-py --wit-path ../../../wit --world reconciler componentize rec -o reconciler.wasm
Component built successfully

Not sure if this is expected, just reporting my experience

**Comment by dicej** [comment]
Hi @henderiw.  Thanks for reporting this.

The issue is that `componentize-py` wants to generate bindings as a Python module with the same name as the world you're targeting, so if your script is _also_ named the same then Python will just use whichever one appears first in the search path (the generated file, in the case).

So it _is_ expected, but the current error diagnostic is clearly not helpful at all.  We should at least print a friendly and actionable error message when the names match, since we know that won't work.  I'll open a PR for that when I have a chance.
